name: Build & deploy 🔥 Ambire Wallet 🔥 (temp wf-tes 🐛)

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development
permissions:
  contents: write
jobs:
  build:
    name: Build & Deploy - (temp wf-tes 🐛)
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }} 
    steps:
    - name: Checkout code 🛎️
      uses: actions/checkout@v3

    - name: Install Node.js ⚙️
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
    - name: Install NPM packages ♾️🕳️
      run: npm ci

    - name: Build project 🛠️
      run: npm run build

    - name: Deploy 🚀🌕 (temp wf-tes 🐛)
      if: github.ref == 'refs/heads/workflow-update'
      uses: JamesIves/github-pages-deploy-action@v4.4.1
      with:
        branch: gh-pages
        folder: build
        target-folder: workflow-update
        cname: wallet.ambire.com