name: Tests (Component and Unit)

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development

jobs:
  tests-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node version️
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install NPM packages
        run: npm ci

      - name: Run tests
        run: npm run test
